"""
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""added end chat support

Revision ID: 537f2b7d4a7c
Revises: 5b5f936cd9e4
Create Date: 2025-03-04 12:07:37.679734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '537f2b7d4a7c'
down_revision: Union[str, None] = '5b5f936cd9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type first
    end_chat_reason_type = postgresql.ENUM(
        'ISSUE_RESOLVED',
        'CUSTOMER_REQUEST',
        'CONFIRMATION_RECEIVED',
        'FAREWELL',
        'THANK_YOU',
        'NATURAL_CONCLUSION',
        'TASK_COMPLETED',
        name='endchatreasontype'
    )
    end_chat_reason_type.create(op.get_bind())

    # Add columns
    op.add_column('agents', sa.Column('ask_for_rating', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('session_to_agents', sa.Column('end_chat_reason', postgresql.ENUM('ISSUE_RESOLVED', 'CUSTOMER_REQUEST', 'CONFIRMATION_RECEIVED', 'FAREWELL', 'THANK_YOU', 'NATURAL_CONCLUSION', 'TASK_COMPLETED', name='endchatreasontype'), nullable=True))
    op.add_column('session_to_agents', sa.Column('end_chat_description', sa.String(), nullable=True))
    op.drop_column('session_to_agents', 'closed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_to_agents', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('session_to_agents', 'end_chat_description')
    op.drop_column('session_to_agents', 'end_chat_reason')
    op.drop_column('agents', 'ask_for_rating')

    # Drop the enum type
    op.execute('DROP TYPE endchatreasontype')
