"""
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""added wlecome header and title 

Revision ID: 7991b4fc00d8
Revises: 6885c9f36712
Create Date: 2025-07-27 16:11:49.392307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7991b4fc00d8'
down_revision: Union[str, None] = '6885c9f36712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('agent_customizations', sa.Column('welcome_title', sa.String(), nullable=True))
    op.add_column('agent_customizations', sa.Column('welcome_subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_customizations', 'welcome_subtitle')
    op.drop_column('agent_customizations', 'welcome_title')


    # ### end Alembic commands ###
