"""
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""added new node type user input

Revision ID: 9ce623009955
Revises: 2fd826882d08
Create Date: 2025-07-25 13:59:26.571283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce623009955'
down_revision: Union[str, None] = '2fd826882d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE nodetype ADD VALUE IF NOT EXISTS 'USER_INPUT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # Create a new enum without the landing_page value
    op.execute("""
        CREATE TYPE nodetype_new AS ENUM (
            'MESSAGE','LLM','CONDITION','FORM','ACTION','HUMAN_TRANSFER','WAIT','END','LANDING_PAGE'
        )
    """)
    
    # Update the column type to use the new enum
    op.execute("ALTER TABLE workflow_nodes ALTER COLUMN node_type TYPE nodetype_new USING node_type::text::nodetype_new")
    
    # Drop the old enum
    op.execute("DROP TYPE nodetype")
    
    # Rename the new enum to the original name
    op.execute("ALTER TYPE nodetype_new RENAME TO nodetype")
    # ### end Alembic commands ###
