"""
Copyright 2024-2026 ChatterMate

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""add_ticket_fields_to_session

Revision ID: ff48f854bcbf
Revises: e65e1b8e7e3c
Create Date: 2025-03-07 11:09:21.933786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff48f854bcbf'
down_revision: Union[str, None] = 'e65e1b8e7e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('session_to_agents', sa.Column('ticket_id', sa.String(), nullable=True))
    op.add_column('session_to_agents', sa.Column('ticket_status', sa.String(), nullable=True))
    op.add_column('session_to_agents', sa.Column('ticket_summary', sa.String(), nullable=True))
    op.add_column('session_to_agents', sa.Column('ticket_description', sa.String(), nullable=True))
    op.add_column('session_to_agents', sa.Column('integration_type', sa.String(), nullable=True))
    op.add_column('session_to_agents', sa.Column('ticket_priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_to_agents', 'ticket_priority')
    op.drop_column('session_to_agents', 'integration_type')
    op.drop_column('session_to_agents', 'ticket_description')
    op.drop_column('session_to_agents', 'ticket_summary')
    op.drop_column('session_to_agents', 'ticket_status')
    op.drop_column('session_to_agents', 'ticket_id')

    # ### end Alembic commands ###
